//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.28 at 07:13:47 PM EST 
//


package org.botgame.db.jaxb.fightlog;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for attackEntry complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="attackEntry">
 *   &lt;complexContent>
 *     &lt;extension base="{}baseEntry">
 *       &lt;sequence>
 *         &lt;element name="Range" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="AttackerDamage" type="{}atkDamage"/>
 *         &lt;element name="DefenderDamage" type="{}dfdDamage"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "attackEntry", propOrder = {
    "range",
    "attackerDamage",
    "defenderDamage"
})
public class AttackEntry
    extends BaseEntry
{

    @XmlElement(name = "Range")
    protected double range;
    @XmlElement(name = "AttackerDamage", required = true)
    protected AtkDamage attackerDamage;
    @XmlElement(name = "DefenderDamage", required = true)
    protected DfdDamage defenderDamage;

    /**
     * Gets the value of the range property.
     * 
     */
    public double getRange() {
        return range;
    }

    /**
     * Sets the value of the range property.
     * 
     */
    public void setRange(double value) {
        this.range = value;
    }

    /**
     * Gets the value of the attackerDamage property.
     * 
     * @return
     *     possible object is
     *     {@link AtkDamage }
     *     
     */
    public AtkDamage getAttackerDamage() {
        return attackerDamage;
    }

    /**
     * Sets the value of the attackerDamage property.
     * 
     * @param value
     *     allowed object is
     *     {@link AtkDamage }
     *     
     */
    public void setAttackerDamage(AtkDamage value) {
        this.attackerDamage = value;
    }

    /**
     * Gets the value of the defenderDamage property.
     * 
     * @return
     *     possible object is
     *     {@link DfdDamage }
     *     
     */
    public DfdDamage getDefenderDamage() {
        return defenderDamage;
    }

    /**
     * Sets the value of the defenderDamage property.
     * 
     * @param value
     *     allowed object is
     *     {@link DfdDamage }
     *     
     */
    public void setDefenderDamage(DfdDamage value) {
        this.defenderDamage = value;
    }

}
