//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.28 at 07:13:47 PM EST 
//


package org.botgame.db.jaxb.fightlog;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for moveEntry complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="moveEntry">
 *   &lt;complexContent>
 *     &lt;extension base="{}baseEntry">
 *       &lt;sequence>
 *         &lt;element name="Location" type="{}XSDPoint"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "moveEntry", propOrder = {
    "location"
})
public class MoveEntry
    extends BaseEntry
{

    @XmlElement(name = "Location", required = true)
    protected XSDPoint location;

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link XSDPoint }
     *     
     */
    public XSDPoint getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link XSDPoint }
     *     
     */
    public void setLocation(XSDPoint value) {
        this.location = value;
    }

}
