//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.28 at 07:13:47 PM EST 
//


package org.botgame.db.jaxb.fightlog;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.botgame.db.jaxb.fightlog package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.botgame.db.jaxb.fightlog
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DfdDamage }
     * 
     */
    public DfdDamage createDfdDamage() {
        return new DfdDamage();
    }

    /**
     * Create an instance of {@link AtkDamage }
     * 
     */
    public AtkDamage createAtkDamage() {
        return new AtkDamage();
    }

    /**
     * Create an instance of {@link BaseEntry }
     * 
     */
    public BaseEntry createBaseEntry() {
        return new BaseEntry();
    }

    /**
     * Create an instance of {@link Log }
     * 
     */
    public Log createLog() {
        return new Log();
    }

    /**
     * Create an instance of {@link XSDPoint }
     * 
     */
    public XSDPoint createXSDPoint() {
        return new XSDPoint();
    }

    /**
     * Create an instance of {@link UserID }
     * 
     */
    public UserID createUserID() {
        return new UserID();
    }

    /**
     * Create an instance of {@link KillEntry }
     * 
     */
    public KillEntry createKillEntry() {
        return new KillEntry();
    }

    /**
     * Create an instance of {@link AttackEntry }
     * 
     */
    public AttackEntry createAttackEntry() {
        return new AttackEntry();
    }

    /**
     * Create an instance of {@link MoveEntry }
     * 
     */
    public MoveEntry createMoveEntry() {
        return new MoveEntry();
    }

}
